sudo: false
language: python
python:
- 2.7
install: pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: RAZ88KJhqm7Imbk9CmkzSMQNNqKbGYjLR25yZ32+rTv1zorizXlvc8A1Kb4Qxti0+DpanbgJNT7/2aRF3kqvH/CiP95Xlbz0ekfw5Npfx3N6FtVYUcRKxRaFRkjbNPx68lrwaDnqp0RHoaRwegqIKctP40IqzJooBozBx/lsbfl1FhGPjLwZJNECINn+WQSysBP6dXtUDPpgdDZXCPvhF4GgmoURW76eRmCryJl5bzQetNekqvq6kxSx7r976N48OgZtpqRdTAeHE0apkesIxsgwl5ZB34jehc8lSh39z4YPCMSVsDLcjIdoRSD2zFo3VZO+56CzqLPR9mk9plTtH0CYXEEz5hyBc8f1tXtOTudeIy/kmCPne99UAarZ5HZ8VU6jxrFE1yX6XsKVhlLgXrRRYwOlPhs/wLSqT3BgcT0guwAXKXWlUatQgkKHx2cvwtCZM8Xar7TjGgmk2SEZ5fLrOyILOm9LNRT8xfdt+6xs86IuJPzI2tUGDfTYfesioxJWgaISbRP7RmpxxPqK/+KAFibOY+Rs7nd+D5YuWhdYsWEOmEJnTjIVrEysJVKpdcyVcHsb+inXreB8na01p+WyGwkOMfoRRI57nF6C3GpHHhAD2oO/sA2LNreGzZ2IWFF2oB/t4OJVUJ7XfEkhSrh4wT7tOVunpkpRgW1+akU=
